### ISSUE TITLE
TypeError: keylogger.start is not a function

### ISSUE THREAD

**Issue by 3DJakob** [aabuhijleh/push-to-talk#2]
I tried running the example code from the readme but I got the error `TypeError: keylogger.start is not a function`. A managed to solve it but I thought I would share how.

<img width="578" alt="Screenshot 2021-10-13 at 15 14 17" src="https://user-images.githubusercontent.com/3826262/137139748-6da2d13a-0dca-42d2-a44b-272eb1651c5f.png">

The program code:
```
import * as keylogger from "keylogger.js";

keylogger.start((key, isKeyUp, keyCode) => {
  console.log("keyboard event", key, isKeyUp, keyCode);
});
```

I managed to solve this issue by changing to require instead of ES6. Very strange issue. I had set `"type": "module"` for import to work. Does anyone know why import would not work?

**Comment by aabuhijleh** [comment]
I just tested it and the issue can be fixed by removing the wildcard import `import * as keylogger from "keylogger.js";` and just importing the module like this `import keylogger from "keylogger.js";` (the default import)

I updated the README. It should be ok now

**Comment by 3DJakob** [comment]
Perfect thank you!
